# Generated by Django 5.2.6 on 2025-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
    ]
